### ISSUE TITLE
Bold Control Button Desync's with keypress commands

### ISSUE THREAD

**Issue by timothycarambat** [Stoick001/jEdit.js#1]
Browser: Chrome 65

When typing in the text editor and attempting to make text bold using the `Ctrl+b` command the bold control does not set to active despite the WYSIWYG now setting text to bold.

**Comment by Stoick001** [comment]
Hi, thanks for the help.
I have found out that multiple controls bold italic and underline did not work, so I added a quick fix for all of them.
